[package]
name = "admin-bridge-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
bridge-service.workspace = true

clap.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
uuid.workspace = true

alloy.workspace = true

directories = "5.0"
url.workspace = true
eyre = "0.6.12"


[lints]
workspace = true
