[package]
name = "m1-da-light-node-verifier"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[features]
integration-tests = []

[dependencies]
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }
tonic-web = { workspace = true }
prost = { workspace = true }
m1-da-light-node-grpc = { workspace = true, features = [] }
m1-da-light-node-util = { workspace = true }
celestia-rpc = { workspace = true }
celestia-types = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
async-stream = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
m1-da-light-node-setup = { workspace = true }
dot-movement = { workspace = true }

[lints]
workspace = true
