services:
  setup:
    image: ghcr.io/movementlabsxyz/suzuka-full-node-setup:${CONTAINER_REV}
    container_name: setup
    environment:
      DOT_MOVEMENT_PATH: /.movement
      # needs to have a connection to the m1-da-light-node
      M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL: ${M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL:?M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL is not set}
      M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME: ${M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME:?M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME is not set}
      M1_DA_LIGHT_NODE_CONNECTION_PORT: ${M1_DA_LIGHT_NODE_CONNECTION_PORT:?M1_DA_LIGHT_NODE_CONNECTION_PORT is not set}
      INDEXER_PROCESSOR_POSTGRES_CONNECTION_STRING: postgres://postgres:password@postgres:5432/postgres
      AWS_REGION: ${AWS_REGION:?AWS_REGION is not set}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MOVEMENT_SYNC: ${MOVEMENT_SYNC:?MOVEMENT_SYNC is not set}
      MAYBE_RUN_LOCAL: "false"
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
      # mount if exists
      - ~/.aws/:/root/.aws:ro

    healthcheck:
      test: [ "CMD-SHELL", "echo 'health check'" ]
      retries: 10
      interval: 10s
      timeout: 5s

  # turn off underlying da light nodes
  celestia-light-node:
    image: busybox
    container_name: celestia-light-node
    command: sleep infinity
    environment:
      - DOT_MOVEMENT_PATH=/.movement
      - CELESTIA_RPC_ADDRESS=celestia-light-node:26657
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    depends_on:
      setup:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "echo 'health check'" ]
      retries: 3
      start_period: 3s
    restart: on-failure:3

  # turn off celestia-light-node-synced
  celestia-light-node-synced:
    image: busybox
    container_name: celestia-light-node-synced
    command: echo "No sync check when following."
    environment:
      - DOT_MOVEMENT_PATH=/.movement
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    depends_on:
      celestia-light-node:
        condition: service_healthy

  # turn off m1-da-light-node
  m1-da-light-node:
    image: busybox
    container_name: m1-da-light-node
    command: sleep infinity
    healthcheck:
      test: [ "CMD-SHELL", "echo 'health check'" ]
      retries: 3
      start_period: 3s

  # turn off suzuka-faucet-service
  suzuka-faucet-service:
    image: busybox
    container_name: suzuka-faucet-service
    command: sleep infinity
    healthcheck:
      test: [ "CMD-SHELL", "echo 'health check'" ]
      retries: 3
      start_period: 3s