version: "3"

environment:

processes:

  mcr-client-tests:
    command: |
      set -e
      cargo run --bin test-mcr-settlement-client
    depends_on:
      eth:
        condition: process_healthy
    availability:
      # NOTE: `restart: exit_on_failure` is not needed since
      # exit_on_end implies it.
      exit_on_end: true