version: "3"

processes:

  setup:
    command: |
      export AWS_REGION=us-west-2
      export MOVEMENT_SYNC="leader::follower-test-$MOVEMENT_SHARED_RANDOM_1<=>{maptos,maptos-storage,movement-da-db}/**"
      movement-full-node-setup
    depends_on:
      build:
        condition: process_completed_successfully
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: echo "true"

  setup-follower-1:
    command: |
      sleep 120
      export AWS_REGION=us-west-2
      export MAYBE_RUN_LOCAL=false
      export MAYBE_DEPLOY_MCR=false
      export MAPTOS_INDEXER_GRPC_LISTEN_PORT=31734
      export MAPTOS_API_CONNECTION_PORT=31731
      export MAPTOS_API_LISTEN_PORT=31731
      export DOT_MOVEMENT_PATH=$DOT_MOVEMENT_PATH-follower-1
      export MOVEMENT_SYNC="follower::follower-test-$MOVEMENT_SHARED_RANDOM_1<=>{maptos,maptos-storage,movement-da-db}/**"
      movement-full-node-setup
    depends_on:
      build:
        condition: process_completed_successfully
      movement-full-node:
        condition: process_healthy
    readiness_probe:
      initial_delay_seconds: 180
      exec:
        command: echo "true"

  movement-full-follower-1:
    command: |
      export DOT_MOVEMENT_PATH=$DOT_MOVEMENT_PATH-follower-1
      movement-full-node
    depends_on:
      movement-celestia-da-light-node:
        condition: process_healthy
      setup-follower-1:
        condition: process_healthy
      movement-full-node:
        condition: process_healthy
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: curl http://0.0.0.0:31731

  setup-follower-2:
    command: |
      sleep 120
      export AWS_REGION=us-west-2
      export MAYBE_RUN_LOCAL=false
      export MAYBE_DEPLOY_MCR=false
      export MAPTOS_INDEXER_GRPC_LISTEN_PORT=32734
      export MAPTOS_API_CONNECTION_PORT=32731
      export MAPTOS_API_LISTEN_PORT=32731
      export DOT_MOVEMENT_PATH=$DOT_MOVEMENT_PATH-follower-2
      export MOVEMENT_SYNC="follower::follower-test-$MOVEMENT_SHARED_RANDOM_1<=>{maptos,maptos-storage,movement-da-db}/**"
      movement-full-node-setup
    depends_on:
      build:
        condition: process_completed_successfully
      movement-full-node:
        condition: process_healthy
    readiness_probe:
      initial_delay_seconds: 180
      exec:
        command: echo "true"

  movement-full-follower-2:
    command: |
      export DOT_MOVEMENT_PATH=$DOT_MOVEMENT_PATH-follower-2
      movement-full-node
    depends_on:
      movement-celestia-da-light-node:
        condition: process_healthy
      setup-follower-2:
        condition: process_healthy
      movement-full-node:
        condition: process_healthy
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: curl http://0.0.0.0:32731

  test-followers-consistent:
    command: |
      cargo run --bin movement-tests-e2e-followers-consistent -- 2
      movement-util syncing delete-resource
    depends_on:
      movement-full-follower-1:
        condition: process_healthy
      movement-full-follower-2:
        condition: process_healthy
      movement-faucet:
        condition: process_healthy
    availability:
      exit_on_end: true