services:

  setup:
    environment:
      ETH_RPC_CONNECTION_PROTOCOL: "http"
      ETH_RPC_CONNECTION_HOSTNAME: "helios"
      ETH_RPC_CONNECTION_PORT: 26657

  helios:
    image: ghcr.io/movementlabsxyz/helios:${CONTAINER_REV}
    container_name: helios
    entrypoint: /app/helios --network ${ETH_NETWORK} --consensus-rpc ${ETH_CONSENSUS_RPC} --execution-rpc ${ETH_EXECUTION_RPC} --checkpoint ${ETH_CHECKPOINT}

    environment:
      # the url for execution
      ETH_NETWORK: ${ETH_NETWORK:?ETH_NETWORK is not set}
      ETH_EXECUTION_RPC: ${ETH_EXECUTION_RPC:?ETH_EXECUTION_RPC is not set}
      ETH_CONSENSUS_RPC: ${ETH_CONSENSUS_RPC:?ETH_CONSENSUS_RPC is not set}
      ETH_CHECKPOINT: ${ETH_CHECKPOINT:?ETH_CHECKPOINT is not set}
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    ports:
      - "26657:26657"
    depends_on:
      setup:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "nc -zv 0.0.0.0 26657" ]