version: "3"

processes:
    
  bridge:
    command: |
      cargo test -p bridge-integration-tests test_movement_event -- --nocapture --test-threads=1
    readiness_probe:
      initial_delay_seconds: 5
      exec:
        command: echo "true"
    depends_on:
      bridge_setup:
        condition: process_healthy
