version: "3"

processes:

  celestia-light-node:
    command: |
      sleep 999999999
    depends_on:
      setup:
        condition: process_healthy
    readiness_probe:
      exec:
        command: echo "true"

  celestia-light-node-synced:
    command: |
      exit 0
    depends_on:
      celestia-light-node:
        condition: process_healthy

  m1-da-light-node:
    command: |
      sleep 999999999
    depends_on:
      celestia-light-node:
        condition: process_healthy
      celestia-light-node-synced:
        condition: process_completed_successfully
    readiness_probe:
      exec:
        command: echo "true"
    
  suzuka-full-node:
    command: |
      suzuka-full-node
    env:
      RUST_LOG: info,aptos-indexer=debug
    depends_on:
      m1-da-light-node:
        condition: process_healthy
    readiness_probe:
      initial_delay_seconds: 10
      exec:
        command: curl http://0.0.0.0:30731

  suzuka-faucet: 
    command : |
      sleep 999999999
    depends_on:
      suzuka-full-node:
        condition: process_healthy
    readiness_probe:
      initial_delay_seconds: 30
      exec:
        command: echo "true"