version: "3"

environment:

processes:

  test-telemetry:
    command: |
      M1_DA_LIGHT_NODE_TRACES_JSON=$(curl http://localhost:16686/api/traces?service=m1-da-light-node)
      # expect the total field to be greater than 0
      if [ $(echo $M1_DA_LIGHT_NODE_TRACES_JSON | jq '.total') -gt 0 ]; then
        echo "M1-DA-Light-Node traces found"
      else
        echo "M1-DA-Light-Node traces not found
        exit 1
      fi

      SUZUKA_TRACES_JSON=$(curl http://localhost:16686/api/traces?service=suzuka-full-node)
      # expect the total field to be greater than 0
      if [ $(echo $SUZUKA_TRACES_JSON | jq '.total') -gt 0 ]; then
        echo "Suzuka traces found"
      else
        echo "Suzuka traces not found
        exit 1
      fi

    depends_on:
      otlp-collector:
        condition: process_healthy
      suzuka-full-node:
        condition: process_healthy
      suzuka-faucet:
        condition: process_healthy
    availability:
      exit_on_end: true
