version: "3"

environment:

processes:

  gas-dos-test:
    command: |
      cargo run --bin suzuka-client-gas-dos
    depends_on:
      suzuka-full-node:
        condition: process_healthy
      suzuka-faucet:
        condition: process_healthy
    availability:
      exit_on_end: true