[package]
name = "m1-da-light-node"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }
tonic-web = { workspace = true }
prost = { workspace = true }
m1-da-light-node-grpc = { workspace = true, features = ["server"] }
m1-da-light-node-util = { workspace = true }
m1-da-light-node-verifier = { workspace = true }
movement-algs = { workspace = true }
movement-types = { workspace = true }
celestia-rpc = { workspace = true }
celestia-types = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
async-stream = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
dot-movement = { workspace = true }
godfig = { workspace = true }
movement-tracing = { workspace = true }
futures = { workspace = true }
bcs = { workspace = true }
zstd = { workspace = true }

# sequencer
memseq = { workspace = true, optional = true }


[features]
default = ["sequencer"]
sequencer = ["memseq"]

[lints]
workspace = true
