[package]
name = "m1-da-light-node-client"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
m1-da-light-node-grpc = { workspace  = true, features = ["client"] }
anyhow = { workspace = true }
tokio-stream = { workspace = true }
movement-types = { workspace = true }
serde_json = { workspace = true }
ecdsa = { workspace = true }
tonic = { workspace = true }   

[features]
sequencer = []

default = [
    "sequencer"
]


[lints]
workspace = true
